init:
  - git config --global core.autocrlf input

version: "{build}"

clone_folder: c:\projects\chrome-material

branches:
  except:
    - master

environment:
  matrix:
  - NODE_VERSION: 5.1.1

cache:
  - "node_modules -> package.json"
  - "src\\node_modules -> src\\package.json"
  - "%APPDATA%\\npm-cache"

install:
  - npm install -g npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM
  - npm install

build_script:
  - node --version
  - npm --version
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm build:win32

test: off

artifacts:
  - path: bin\*

# deploy:
# .......