init:
  - git config --global core.autocrlf input

version: "{build}"

clone_folder: c:\projects\chrome-material

branches:
  only:
    - release

cache:
  - "node_modules -> package.json"
  - "src\\node_modules -> src\\package.json"
  - "%APPDATA%\\npm-cache"

install:
  - npm install -g npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build_script:
  - node --version
  - npm --version
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm run build:win32

after_build:
  - 7z a Chrome-win32-ia32.zip %APPVEYOR_BUILD_FOLDER%\bin\Chrome-win32-ia32\
  - 7z a Chrome-win32-x64.zip %APPVEYOR_BUILD_FOLDER%\bin\Chrome-win32-x64\

test: off

artifacts:
  - path: Chrome-win32-ia32.zip

  - path: Chrome-win32-x64.zip

deploy:
  provider: GitHub
  auth_token:
    secure: FDEPDmc5y196/bX8kaD370vHyQU598nb6TR0XUfUMARTgzRtopoW/eOEphFdMaYv
  artifact: /.*\.zip/
  draft: true
  on:
    branch: release